### PR TITLE
Fix recursive creation of less files on init

### LINKED ISSUE #53: Less files in subfolders are not created on initial run
NPM - less-watch-compiler v1.10.2

Steps to reproduce:
- Delete the public folder
- Create file in subfolder src/css/file1.less
- Create file in subfolder src/css/subfolder/file2.less
- Command: less-watch-compiler src/css public/css

Actual Results:
- public/css/file1.css is created
- The "subfolder" and "file2.css" are not created

Expected Results:
- "subfolder" and "file2.css" are created on first run

Note:
- If you modify "file2.css" then it will be created

Diagnosis:
- I think that on line #58 of src/lib/lessWatchCompilerUtils.js
```lessWatchCompilerUtilsModule.walk(f, options, callback);```
Should include the initCallback
```lessWatchCompilerUtilsModule.walk(f, options, callback, initCallback);```

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
Fixes #53 & #55

- [x] Did you add adequate test and make sure they pass by running `npm run test`
no new tests
- [x] Did you add update docs in the `README.md` file?
no changes

### CODE REVIEW

**Comment by jonycheung** [comment]
Thanks! @JamesMcIntosh  I'll review this PR this week.

File: src/less-watch-compiler.js [hunk 1]
```diff
@@ -114,9 +114,15 @@ function init(){
       } else {
         // f is a new file or changed
         var importedFile = false;
+        var filename = f.substring(lessWatchCompilerUtils.config.watchFolder.length+1)
         for (var i in fileimportlist){
           for (var k in fileimportlist[i]){
-            if (f.substring(lessWatchCompilerUtils.config.watchFolder.length+1) == fileimportlist[i][k]){
+            var hasExtension = fileimportlist[i][k].substring(fileimportlist[i][k].lastIndexOf('/') + 1).indexOf('.') != -1;
```
Comment (jonycheung) [inline src/less-watch-compiler.js]: What is this doing here?

Comment (JamesMcIntosh) [reply src/less-watch-compiler.js]: A checks to see if the filename has an extension, if not it assumes that it is a .less file.
See point 3 in #55, it has a link to the less documentation.
