### PR TITLE
Better path resolving

### LINKED ISSUE #60: Compiler creating css in wrong directory
Are you using the command line tool `less-watch-compiler`?  **Yes**
If you are using the command line tool, which version are you using (`less-watch-compiler --version` to find out)? **1.11.0**
Is the issue reproducible after updating to the latest version (` npm update less-watch-compiler`)? **Yes**

Steps to reproduce:

1. Upgrade from 1.8.0 to 1.11.0
1. Watch LESS, with npm: `"less-watch-compiler src/less public/css"`
1. Edit any file

Actual Results:
- Output is created in the wrong directory. It appears to be concatenating the arguments weirdly. 

> The file: src\less\index.less was changed. Recompiling public/csssrc\less/index.css at 19:28:34 on 06/03/2018

Expected Results:
- Output to be created in `public/css/index.css`

Note:
This is on Windows

### PR DESCRIPTION
**Pull request by Misiur**
Fixes #60 

- [X] Did you add adequate test and make sure they pass by running `npm run test`
- [ ] Did you add update docs in the `README.md` file?

Changes proposed in this pull request:
- Added better path resolving system. 
- Allows main file to be outside `source_dir`, outputs it to root of `output_dir`. Does *not* make it watchable, I didn't want to make this PR too overblown

I did not touch other path related resolving parts, which may not resolve some of the path related issues.
Also to not touch other testcases it uses relative paths as arguments passed to `lessc`, I can change that to use absolute paths instead if anybody is interested.

### CODE REVIEW

File: src/lib/lessWatchCompilerUtils.js [hunk 1]
```diff
@@ -117,6 +114,35 @@ define(function (require) {
       };
 
     },
+    resolveOutputPath: function (filePath) {
```
Comment (jonycheung) [inline src/lib/lessWatchCompilerUtils.js]: I would love a test for this function and remove references to `lessWatchCompilerUtilsModule`... but it's not consistent everywhere else anyways.

File: src/lib/lessWatchCompilerUtils.js [hunk 2]
```diff
@@ -117,6 +114,35 @@ define(function (require) {
...
+      var fullPath = path.resolve(filePath);
+      var parsedPath = path.parse(fullPath);
+
+      // Only empty when unit testing it seems
+      var relativePath = null;
+      var dirname = null;
+      if (lessWatchCompilerUtilsModule.config.watchFolder) {
```
Comment (jonycheung) [inline src/lib/lessWatchCompilerUtils.js]: remove `lessWatchCompilerUtilsModule`

**Comment by jonycheung** [comment]
I'm going to merge this as is. Thanks for the awesome work.

This may fix #71
